// /**
//  * Corresponds to the `users` table.
//  * Includes all database fields from your original schema.
//  */
// export type BackendUser = {
//     readonly id: number;              // INT UNSIGNED NOT NULL AUTO_INCREMENT
//     first_name: string;               // VARCHAR(64) NOT NULL
//     last_name: string;                // VARCHAR(64) NOT NULL
//     username: string;                 // VARCHAR(64) NOT NULL
//     email: string;                    // VARCHAR(256) NOT NULL
//     image_filename: string | null;    // VARCHAR(128) DEFAULT NULL
//     password: string;                 // VARCHAR(255) NOT NULL
//     auth_token: string | null;        // CHAR(64) DEFAULT NULL

//     // Location fields (stored directly on the user table)
//     city: string | null;              // VARCHAR(128) DEFAULT NULL
//     country_code: string | null;      // CHAR(2) DEFAULT NULL

//     is_hidden: 0 | 1;                 // TINYINT(1) NOT NULL (0 for false, 1 for true)

//     // Timestamps
//     created_at: Date;                 // TIMESTAMP
//     updated_at: Date;                 // TIMESTAMP
// };

// /**
//  * Corresponds to the `genres` table.
//  */
// export type BackendGenre = {
//     readonly id: number;              // INT UNSIGNED NOT NULL AUTO_INCREMENT
//     name: string;                     // VARCHAR(64) NOT NULL
//     parent_id: number | null;         // INT UNSIGNED DEFAULT NULL (Self-referencing FK)
// };

// /**
//  * Corresponds to the `social_network` lookup table.
//  */
// export type BackendSocialNetwork = {
//     readonly id: number;              // INT UNSIGNED NOT NULL AUTO_INCREMENT
//     slug: string;                     // VARCHAR(32) NOT NULL
//     label: string;                    // VARCHAR(64) NOT NULL
//     url_mask: string | null;          // VARCHAR(256) DEFAULT NULL
//     handle_re: string | null;         // VARCHAR(256) DEFAULT NULL
// };

// /**
//  * Corresponds to the `social_links` table.
//  */
// export type BackendSocialLink = {
//     readonly id: number;              // INT UNSIGNED NOT NULL AUTO_INCREMENT
//     user_id: number;                  // FK to BackendUser
//     network_id: number;               // FK to BackendSocialNetwork
//     url: string;                      // VARCHAR(512) NOT NULL
//     handle: string | null;            // VARCHAR(128) DEFAULT NULL
//     is_public: 0 | 1;                 // TINYINT(1) NOT NULL
//     created_at: Date;                 // TIMESTAMP
// };

// /**
//  * Corresponds to the `user_genres` junction table (Many-to-Many).
//  */
// export type BackendUserGenre = {
//     user_id: number;                  // PK part, FK to BackendUser
//     genre_id: number;                 // PK part, FK to BackendGenre
// };

// /**
//  * Type for creating a new user (POST /api/users).
//  * Omitted fields: id (auto-generated), auth_token (generated by server), and timestamps.
//  */
// export type UserCreationPayload = {
//     first_name: string;
//     last_name: string;
//     username: string;
//     email: string;
//     password: string; // Plain password before hashing

//     image_filename?: string | null; // Optional fields
//     city?: string | null;
//     country_code?: string | null;
//     is_hidden?: 0 | 1;
// };